apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-a
spec:
  replicas: 3
  selector:
    app: nginx-a
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-a
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80